# -*- coding: utf-8 -*-
"""task1_data_collection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iylg_hI8OFu-AaE0Q-fLJnDYhX163k9Q
"""

import requests
import time
import json
import os
from datetime import datetime

headers = {"User-Agent": "TrendPulse/1.0"}
url = "https://hacker-news.firebaseio.com/v0/topstories.json"
response = requests.get(url, headers=headers)

story_ids = response.json()[:500]

print("Fetched", len(story_ids), "story IDs")
print("Sample IDs:", story_ids[:10])

test_ids = story_ids[:500]   # start with 200 IDs for testing

categories = {
    "technology": ["ai","software","tech","code","computer","data","cloud","api","gpu","llm"],
    "worldnews": ["war","government","country","president","election","climate","attack","global"],
    "sports": ["nfl","nba","fifa","sport","game","team","player","league","championship"],
    "science": ["research","study","space","physics","biology","discovery","nasa","genome"],
    "entertainment": ["movie","film","music","netflix","game","book","show","award","streaming"]
}

def fetch_story(story_id):
    try:
        url = f"https://hacker-news.firebaseio.com/v0/item/{story_id}.json"
        response = requests.get(url, headers=headers, timeout=5)
        if response.status_code == 200:
            return response.json()
        else:
            print(f"Failed to fetch story {story_id}")
            return None
    except Exception as e:
        print(f"Error fetching {story_id}: {e}")
        return None

def assign_category(title):
    title_lower = title.lower()
    for category, keywords in categories.items():
        if any(keyword in title_lower for keyword in keywords):
            return category
    return None

def extract_fields(story, category):
    return {
        "id": story.get("id"),
        "title": story.get("title"),
        "url": story.get("url"),
        "score": story.get("score"),
        "time": story.get("time"),
        "category": category
    }

stories_output = []

for category in categories.keys():
    count = 0
    for story_id in test_ids:
        if count >= 25:
            break
        story = fetch_story(story_id)
        time.sleep(0.2)  # shorter pause
        if story and "title" in story:
            assigned = assign_category(story["title"])
            if assigned == category:
                record = extract_fields(story, assigned)
                stories_output.append(record)
                count += 1
    time.sleep(2)  # pause after each category loop

print("Collected", len(stories_output), "stories")

os.makedirs("data", exist_ok=True)
filename = f"data/trends_{datetime.now().strftime('%Y%m%d')}.json"

with open(filename, "w", encoding="utf-8") as f:
    json.dump(stories_output, f, indent=4)

print(f"Saved {len(stories_output)} stories to {filename}")

with open(filename, "r", encoding="utf-8") as f:
    data_preview = json.load(f)

# Show first 3 stories
for story in data_preview[:3]:
    print(story)

test_ids = story_ids[:500]   # use all IDs

stories_output = []

for category in categories.keys():
    count = 0
    for story_id in test_ids:
        if count >= 25:
            break
        story = fetch_story(story_id)
        time.sleep(0.1)
        if story and "title" in story:
            assigned = assign_category(story["title"])
            if assigned == category:
                record = extract_fields(story, assigned)
                stories_output.append(record)
                count += 1
    time.sleep(2)

print("Collected", len(stories_output), "stories")

os.makedirs("data", exist_ok=True)
filename = f"data/trends_{datetime.now().strftime('%Y%m%d')}.json"

with open(filename, "w", encoding="utf-8") as f:
    json.dump(stories_output, f, indent=4)

print(f"Saved {len(stories_output)} stories to {filename}")

from collections import Counter

category_counts = Counter([s["category"] for s in stories_output])
print(category_counts)